export const FILTER_ADDRESS_CONTENT = [
  {
    value: "",
    type: "select",
    name: "country",
    placeholder: "Davlatni tanlang",
    options: ["Uzbekiston", "Rossiya", "TAMAM"],
  },
  {
    value: "",
    type: "select",
    name: "region",
    placeholder: "Viloyatni tanlang",
    options: [
      "Toshkent",
      "Toshkent viloyati",
      "Navoiy",
      "Samarqand",
      "Buxoro",
      "Andijon",
      "Fargʻona",
      "Namangan",
      "Qarshi",
      "Xiva",
      "Urganch",
      "Termiz",
      "Moskva",
      "Sankt-Peterburg",
      "Nursulton",
      "Almaty",
    ],
  },
  {
    value: "",
    type: "text",
    name: "address",
    placeholder: "Manzil boyicha",
  },
];
