export const FILTER_ADDRESS_CONTENT = [
  {
    value: "",
    type: "select",
    name: "country",
    placeholder: "Davlatni tanlang",
    options: ["Uzbekiston", "Rossiya", "TAMAM"],
  },
  {
    value: "",
    type: "select",
    name: "region",
    placeholder: "Viloyatni tanlang",
    options: ["Toshkent", "Toshkent viloyati", "Navoiy", "Samarqand"],
  },
  {
    value: "",
    type: "text",
    name: "address",
    placeholder: "Manzil boyicha",
  },
  {
    value: "",
    type: "select",
    name: "entryYear",
    placeholder: "Kirgan yil",
    options: ["2020/2021", "2021/2022", "2022/2023", "2023/2024", "2024/2025"],
  },
  {
    value: "",
    type: "select",
    name: "educationForm",
    placeholder: "Ta'lim turi",
    options: ["Sirtqi", "Kundizgi", "Ertalapki"],
  },
  {
    value: "",
    type: "select",
    name: "languageCertificate",
    placeholder: "Til sertificat",
    options: ["IELTS", "TOIFEL", "DUALINGO"],
  },
  {
    value: "",
    type: "select",
    name: "semester",
    placeholder: "Oqiyotgan semestr",
    options: ["1", "2", "3", "4", "5", "6"],
  },
  {
    value: "",
    type: "text",
    name: "scientificSupervisor",
    placeholder: "Ilmiy rahbar ismi",
  },
  {
    value: "",
    type: "text",
    name: "scientificAdvisor",
    placeholder: "Ilmiy maslahatchi ismi",
  },
  {
    value: "",
    type: "text",
    name: "internshipSupervisor",
    placeholder: "Amaliyot rahbar ismi",
  },
  {
    value: "",
    type: "text",
    name: "internalReviewer",
    placeholder: "Ichiki taqsischi",
  },
  {
    value: "",
    type: "text",
    name: "externalReviewer",
    placeholder: "Tashqi taqsischi",
  },
  {
    value: "",
    type: "text",
    name: "thesisTopic",
    placeholder: "Thesis Topic",
  },
  {
    value: "",
    type: "text",
    name: "academicLeave",
    placeholder: "Akademik dam",
    options: ["Olgan", "Olmagan"],
  },
];
