export const FILTER_FACULTY_CONTENT = [
  {
    value: "",
    type: "select",
    name: "facultyName",
    placeholder: "Mutaxassislikni tanlang",
    options: [
      "Matematik analiz",
      "Algebra va funksional analiz",
      "Geometriya va topologiya",
      "Differensial tenglamalar va matematik fizika",
      "Ehtimollar nazariyasi va matematik statistika",
      "Mexanika va matematik modellashtirish",
      "Sun'iy intellekt kafedrasi",
      "Amaliy matematika va kompyuter tahlili",
      "Algoritmlar va dasturlash texnologiyalari",
      "Axborot xavfsizligi",
      "Hisoblash matematikasi va axborot tizimlari",
      "Nazariy fizika",
      "Yadro fizikasi",
      "Yarimo'tkazgichlar va polimerlar fizikasi",
      "Fotonika",
      "Umumiy fizika",
      "Astronomiya va astrofizika",
    ],
  },
];
