export const FILTER_Master_CONTENT = [
  {
    value: "",
    type: "text",
    name: "firstName",
    placeholder: "Ism kiriting",
  },
  {
    value: "",
    type: "text",
    name: "middleName",
    placeholder: "Otasining ismini kiriting",
  },
  {
    value: "",
    type: "text",
    name: "lastName",
    placeholder: "Familiya kiriting",
  },
  {
    value: "",
    type: "text",
    name: "jshshr",
    placeholder: "JSHSHIR kiriting",
  },
  {
    value: "",
    type: "text",
    name: "passportNumber",
    placeholder: "Passport raqami va seriyasi",
  },
  {
    value: "",
    type: "text",
    name: "dateOfBirth",
    placeholder: "Yil-oy-kun",
  },
  {
    value: "Jins tanlnang",
    type: "select",
    name: "gender",
    placeholder: "Jins tanlnang",
    options: ["Erkak", "Ayol"],
  },
  {
    value: "",
    type: "select",
    name: "nationality",
    placeholder: "Millatini kiriting (uzbek)",
    options: ["uzbek", "russ", "qozo"],
  },
  {
    value: "",
    type: "email",
    name: "email",
    placeholder: "Emailini kiriting",
  },
  {
    value: "",
    type: "text",
    name: "phoneNumber",
    placeholder: "Raqamni kirting",
  },
  {
    value: "",
    type: "text",
    name: "parentPhoneNumber",
    placeholder: "Ota-onasini raqamni kirting",
  },
];
