export const tableHead: Array<string> = [
  "#",
  "Id",
  "Ismi",
  "Familiya",
  "Otasini ismi",
  "Passport raqami",
  "JSHSHR",
  "Tug'ilgan sanasi",
  "Jinsi",
  "Millati",
  "Email",
  "Telefon raqami",
  "Ota-ona raqami",
];