export const tableHead: Array<string> = [
  "#",
  "Id",
  "Ismi",
  "Familiya",
  "Otasini ismi",
  "Passport raqami",
  "JSHSHR",
  "Tug'ilgan sanasi",
  "Jinsi",
  "Millati",
  "Email",
  "Telefon raqami",
  "Ota-ona raqami",
  "Shahri",
  "Region",
  "Manzil",
  // education
  "Akademik Ta'titl",
  "Ilmiy amaliyot o'tash joyi",
  "Kurs ",
  "Fakultet",
  "Ta'lim turi",
  "Kirgan yil",
  "Tashqi taqzischi",
  "Ichki taqzischi",
  "Amaliyot rahbar ",
  "Til sertificat",
  "Tolov turini",
  "Ilmiy rahbar ",
  "Ilmiy maslahatchi ",
  "O`qiyotgan semestr",
  "Dissertatsiya mavzusi",
  // bachelor
  "Tugatgan OTM nomi",
  "Tugatgan yili",
  "Diplom raqami",
  "Tugatgan mutaxasisligi",
  // article
  "Birinchi maqola nomi",
  "Birinchi maqola file nomi",
  "Birinchi maqola chop etilgan sana",
  "Birinchi maqola chop etilgan jurnal",
  "Ikkinchi maqola nomi",
  "Ikkinchi maqola file nomi",
  "Ikkinchi maqolani chop etilgan jurnal",
  "Ikkinchi maqola chop etilgan sana",
  // fakultet
  "Mutaxassislik nomi",
];
